### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by micheltol** [captainjono/SlothBot#1]
What are your plans for SlothBot framework?
Any plans on extending the framework more in the direction of more handlers, plugins, tests or is it a one off project?

**Comment by captainjono** [comment]
My initial motivation for the project was the need to use slack as an
integration layer - much like a a http webapi. I don't really see it being
in the business of creating plugins / message handlers for specific
scenarios outside of these bounds. Have u any specific scenarios u are
interested in?

With this in mind i would like to provide features which makes interacting
with slothbot a fluent person like experience. So supporting saga style
message handlers where your message handier may gather information over
multiple stages is something im actively thinking about.

Ie.
``
Me: check api status
sb: api is not responding, would to like to reboot the server?
Me: yep!
Sb: rebooting server
....
Sb: api took 200ms to respond
``
The next user story i want to implement though will be for legacy codebases
where u can't compile slothbot into it for weather reason  - shell
commanding, .dll interop

"I have an existing program i want to expose over slack to a subset of
users."
``
Me: let me call "ping.exe server.com" with "check status server"
Sb: which users can access this command?
Me: anyone
Sb: cool, ready for "check status server"
``
Im going to start this when I'm back from holidays in December, which is
when ill get some tests done too!
